### ISSUE TITLE
Invalid host headers

### ISSUE THREAD

**Issue by ajinkyapuar** [xorsnn/altexo-chat-web#3]
Trying to access the app on a mobile device while it run locally on the desktop

On Desktop 
terminal: `npm run start`
browser: `localhost:3000`

On Mobile
browser: `IP:3000`

Result
Invalid Host header

**Comment by xorsnn** [comment]
@ajinkyapuar this should fix the issue 986d0cb28989010222e5c1561f53b93d8a5ba263 , closing.
